function [PTFvalue, quantityCall, idxCall, quantityPut, idxPut, cashFlow, spesaBidAsk] = ...
    Vega_hedging(PTFvalue, VegaUpSensitivity, ...
                 alpha, CallexpDates, PutexpDates, timegrid, ...
                 askCall, bidCall, askPut, bidPut, ...
                 disc, dates, CallStrikes, PutStrikes, fwd_prices, ...
                 eta, kappa, sigma, eta_omega, kappa_omega, sigma_omega, t0, CallPrices, ...
                 PutPrices,eta_Vega, kappa_Vega, sigma_Vega, idxCallEta, quantityCallEta, flag, idxC, idxP)

    % Tolleranza per neutralità in eta
    eps = 100;
    
    % Calcolo le vega
    ValueChangeCall = vegaSensitivitycall( ...
        alpha, CallexpDates, bidCall, disc, dates, ...
        CallStrikes, fwd_prices, eta, kappa, sigma, ...
        eta_Vega, kappa_Vega, sigma_Vega, t0);

    ValueChangePut = vegaSensitivityput( ...
        alpha, PutexpDates, bidPut, disc, dates, ...
        PutStrikes, fwd_prices, eta, kappa, sigma, ...
        eta_Vega, kappa_Vega, sigma_Vega, t0);
    ValueChangeCallEta = etaSensitivitycall(alpha, CallexpDates, CallPrices, disc, dates, CallStrikes, fwd_prices, eta, kappa, sigma, eta_omega, kappa_omega, sigma_omega, t0);
    ValueChangePutEta = etaSensitivityput(alpha, PutexpDates, PutPrices, disc, dates, PutStrikes, fwd_prices, eta, kappa, sigma, eta_omega, kappa_omega, sigma_omega, t0);
    % Hedging: scelgo il put ottimale dato il call idxCall
    [cashFlow,idxCall, idxPut, quantityPut, quantityCall, spesaBidAsk] = ...
        selectOptimalPutGivenCall(VegaUpSensitivity+ValueChangeCall(idxCallEta)*quantityCallEta, CallexpDates, PutexpDates, timegrid, ...
                                  askCall, bidCall, askPut, bidPut, ...
                                  ValueChangeCall, ValueChangePut, ...
                                  ValueChangeCallEta, ValueChangePutEta, eps, flag, idxC, idxP);

    % Aggiorno il valore del portafoglio sottraendo il cash flow dell'hedge
    PTFvalue = PTFvalue - cashFlow;

end

